#SERVER-CFG
server:
  port: 2023

#MONGO-CFG
spring:
  data:
    mongodb:
      port: 27017
      uri: mongodb://localhost:27017/generate-project
      database: generate-project

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
